#ifndef FSA_RT_LOG_VERSION_H
#define FSA_RT_LOG_VERSION_H

#define FSA_RT_LOG_VER_MAJOR 0
#define FSA_RT_LOG_VER_MINOR 0
#define FSA_RT_LOG_VER_PATCH 1

#define FSA_RT_LOG_VER \
    VERSION_PACK(FSA_RT_LOG_VER_MAJOR, FSA_RT_LOG_VER_MINOR, FSA_RT_LOG_VER_PATCH)
#define FSA_RT_LOG_VER_STRING \
    VERSION_STRING(FSA_RT_LOG_VER_MAJOR, FSA_RT_LOG_VER_MINOR, FSA_RT_LOG_VER_PATCH)

#endif // FSA_RT_LOG_VERSION_H
