/*---------------------------------- PARAM LIST ----------------------------------*/
#define RMAIO_ADDR_PARAM_LIST_BASE                         0 // 参数列表基地址

#define RMAIO_ADDR_PARAM_LIST_SAVE                         (RMAIO_ADDR_PARAM_LIST_BASE + 0) // 写入0x33333333，参数保存

#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE               (RMAIO_ADDR_PARAM_LIST_BASE + 1)           // 执行器基础参数
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_DIRCTION           (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 0) // 方向
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_OUTPUT_SHAFT_RATIO (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 1) // 减速比
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_MAX_POS_RAD        (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 2) // 最大位置
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_MIN_POS_RAD        (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 3) // 最小位置
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_MAX_VEL_RAD_S      (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 4) // 最大速度
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_MAX_CUR_A          (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 5) // 最大电流
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_MAX_TORQUE_NM      (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 6) // 最大力矩
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_MAX_ACC_RAD_SS     (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 7) // 最大加速度
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_PVCT_INTERFACE_LPF_WC_V1 \
        (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 8) // 位置反馈滤波器截止频率
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_PVCT_INTERFACE_LPF_WC_V2 \
        (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 9) // 速度反馈滤波器截止频率
#define RMAIO_ADDR_ACTUATOR_BASE_PARAMS_PVCT_INTERFACE_LPF_WC_V3 \
        (RMAIO_ADDR_ACTUATOR_BASE_PARAMS_BASE + 10) // 电流/力矩反馈滤波器截止频率

#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE (RMAIO_ADDR_PARAM_LIST_BASE + 76) // 执行器传感器参数
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_0_0 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 0) // coil_ntc_param[0][0]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_0_1 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 1) // coil_ntc_param[0][1]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_0_2 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 2) // coil_ntc_param[0][2]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_0_3 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 3) // coil_ntc_param[0][3]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_0_4 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 4) // coil_ntc_param[0][4]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_1_0 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 5) // coil_ntc_param[1][0]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_1_1 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 6) // coil_ntc_param[1][1]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_1_2 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 7) // coil_ntc_param[1][2]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_1_3 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 8) // coil_ntc_param[1][3]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_1_4 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 9) // coil_ntc_param[1][4]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_2_0 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 10) // coil_ntc_param[2][0]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_2_1 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 11) // coil_ntc_param[2][1]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_2_2 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 12) // coil_ntc_param[2][2]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_2_3 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 13) // coil_ntc_param[2][3]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_2_4 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 14) // coil_ntc_param[2][4]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_3_0 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 15) // coil_ntc_param[3][0]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_3_1 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 16) // coil_ntc_param[3][1]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_3_2 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 17) // coil_ntc_param[3][2]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_3_3 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 18) // coil_ntc_param[3][3]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_COIL_NTC_PARAM_3_4 \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 19) // coil_ntc_param[3][4]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_0_0 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 20) // mos_ntc_param[0][0]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_0_1 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 21) // mos_ntc_param[0][1]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_0_2 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 22) // mos_ntc_param[0][2]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_0_3 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 23) // mos_ntc_param[0][3]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_0_4 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 24) // mos_ntc_param[0][4]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_1_0 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 25) // mos_ntc_param[1][0]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_1_1 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 26) // mos_ntc_param[1][1]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_1_2 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 27) // mos_ntc_param[1][2]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_1_3 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 28) // mos_ntc_param[1][3]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_1_4 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 29) // mos_ntc_param[1][4]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_2_0 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 30) // mos_ntc_param[2][0]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_2_1 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 31) // mos_ntc_param[2][1]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_2_2 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 32) // mos_ntc_param[2][2]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_2_3 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 33) // mos_ntc_param[2][3]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_2_4 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 34) // mos_ntc_param[2][4]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_3_0 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 35) // mos_ntc_param[3][0]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_3_1 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 36) // mos_ntc_param[3][1]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_3_2 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 37) // mos_ntc_param[3][2]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_3_3 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 38) // mos_ntc_param[3][3]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_MOS_NTC_PARAM_3_4 (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 39) // mos_ntc_param[3][4]
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_FOC_SENSOR_TYPE   (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 40) // FOC传感器类型
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_FOC_SENSOR_IS_REVERSAL \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 41) // FOC传感器是否反向
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_OUTPUT_SHAFT_SENSOR_TYPE \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 42) // 出轴传感器类型
#define RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_OUTPUT_SHAFT_SENSOR_IS_REVERSAL \
        (RMAIO_ADDR_ACTUATOR_SENSOR_PARAMS_BASE + 43) // 出轴传感器是否反向

#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE         (RMAIO_ADDR_PARAM_LIST_BASE + 136)            // 执行器控制参数
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_POS_LOOP_DIV (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 0) // 位置环分频
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_POS_KP       (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 1) // 位置控制比例增益
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_POS_KD       (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 2) // 位置控制微分增益
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_VEL_LOOP_DIV (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 3) // 速度环分频
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_VEL_KP       (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 4) // 速度控制比例增益
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_VEL_KI       (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 5) // 速度控制积分增益
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_VEL_FDBK_LPF_WC \
        (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 6) // 速度反馈低通滤波截止频率
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_CUR_LOOP_DIV (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 7) // 电流环分频
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_CUR_LOOP_WC  (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 8) // 电流环带宽
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_CUR_LOOP_LOW_FREQ_GAIN \
        (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 9)                                                          // 电流环低频增益
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_PD_LOOP_DIV          (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 10) // PD环分频
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_PD_KP                (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 11) // PD控制比例增益
#define RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_PD_KD                (RMAIO_ADDR_ACTUATOR_CONTROL_PARAMS_BASE + 12) // PD控制微分增益

#define RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_BASE                    (RMAIO_ADDR_PARAM_LIST_BASE + 165)         // 执行器功能参数
#define RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_CTRL_MODE               (RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_BASE + 0) // 控制模式
#define RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_FOC_THETA_SORCE         (RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_BASE + 1) // FOC角度源选择
#define RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_FRICTION_COMP_ENABLE    (RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_BASE + 2) // 摩擦补偿使能
#define RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_TORQUE_LOAD_COMP_ENABLE (RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_BASE + 3) // 负载转矩补偿
#define RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_COGGING_COMP_ENABLE     (RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_BASE + 4) // 齿槽转矩补偿使能
#define RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_OUT_SHAFT_SENSOR_ENABLE (RMAIO_ADDR_ACTUATOR_FUNC_PARAMS_BASE + 5) // 输出轴编码器使能

#define RMAIO_ADDR_MOTOR_PARAMS_BASE                            (RMAIO_ADDR_PARAM_LIST_BASE + 187) // 电机参数
#define RMAIO_ADDR_MOTOR_PARAMS_NPP                             (RMAIO_ADDR_MOTOR_PARAMS_BASE + 0) // 极对数
#define RMAIO_ADDR_MOTOR_PARAMS_RS                              (RMAIO_ADDR_MOTOR_PARAMS_BASE + 1) // 相电阻
#define RMAIO_ADDR_MOTOR_PARAMS_LD                              (RMAIO_ADDR_MOTOR_PARAMS_BASE + 2) // D轴电感
#define RMAIO_ADDR_MOTOR_PARAMS_LQ                              (RMAIO_ADDR_MOTOR_PARAMS_BASE + 3) // Q轴电感
#define RMAIO_ADDR_MOTOR_PARAMS_FLUX_WB                         (RMAIO_ADDR_MOTOR_PARAMS_BASE + 4) // 磁链系数
#define RMAIO_ADDR_MOTOR_PARAMS_KV_COEF                         (RMAIO_ADDR_MOTOR_PARAMS_BASE + 5) // KV值
#define RMAIO_ADDR_MOTOR_PARAMS_ROTOR_INERTIA                   (RMAIO_ADDR_MOTOR_PARAMS_BASE + 6) // 转子惯量

#define RMAIO_ADDR_HARDWARE_PARAMS_BASE                         (RMAIO_ADDR_PARAM_LIST_BASE + 210)     // 硬件参数
#define RMAIO_ADDR_HARDWARE_PARAMS_ADC_FULL_VAL                 (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 0)  // ADC最大值
#define RMAIO_ADDR_HARDWARE_PARAMS_TIMER_FREQ_MHZ               (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 1)  // 定时器频率
#define RMAIO_ADDR_HARDWARE_PARAMS_IS_CENTER_ALIGN              (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 2)  // 是否为中央对齐模式
#define RMAIO_ADDR_HARDWARE_PARAMS_PWM_FREQ_KHZ                 (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 3)  // PWM频率
#define RMAIO_ADDR_HARDWARE_PARAMS_VBUS_RANGE                   (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 4)  // 母线电压范围
#define RMAIO_ADDR_HARDWARE_PARAMS_PHASE_CUR_RANGE              (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 5)  // 相电流范围
#define RMAIO_ADDR_HARDWARE_PARAMS_PHASE_CUR_OFFSET             (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 6)  // 相电流偏置
#define RMAIO_ADDR_HARDWARE_PARAMS_PHASE_VOL_RANGE              (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 7)  // 相电压范围
#define RMAIO_ADDR_HARDWARE_PARAMS_SAMPING_RS_NUM               (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 8)  // 采样电阻数量
#define RMAIO_ADDR_HARDWARE_PARAMS_DEAD_TIME_NS                 (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 9)  // 死区时间
#define RMAIO_ADDR_HARDWARE_PARAMS_CUR_AMP_GAIN                 (RMAIO_ADDR_HARDWARE_PARAMS_BASE + 10) // 电流放大增益

#define RMAIO_ADDR_FORCE_PARAMS_BASE                            (RMAIO_ADDR_PARAM_LIST_BASE + 237) // 强拖控制参数
#define RMAIO_ADDR_FORCE_PARAMS_ACC_RAD_SS                      (RMAIO_ADDR_FORCE_PARAMS_BASE + 0) // 强拖加速度
#define RMAIO_ADDR_FORCE_PARAMS_ELEC_VELOCITY_HZ                (RMAIO_ADDR_FORCE_PARAMS_BASE + 1) // 强拖速度
#define RMAIO_ADDR_FORCE_PARAMS_THETA_RAD                       (RMAIO_ADDR_FORCE_PARAMS_BASE + 2) // 强拖角度
#define RMAIO_ADDR_FORCE_PARAMS_CURRENT                         (RMAIO_ADDR_FORCE_PARAMS_BASE + 3) // 强拖电流
#define RMAIO_ADDR_FORCE_PARAMS_VOLTAGE                         (RMAIO_ADDR_FORCE_PARAMS_BASE + 4) // 强拖电压

#define RMAIO_ADDR_FLUX_OBS_PARAMS_BASE                         (RMAIO_ADDR_PARAM_LIST_BASE + 258)    // 无感控制参数
#define RMAIO_ADDR_FLUX_OBS_PARAMS_PLL_WC_HZ                    (RMAIO_ADDR_FLUX_OBS_PARAMS_BASE + 0) // 锁相环带宽
#define RMAIO_ADDR_FLUX_OBS_PARAMS_CRITICAL_VEL_HZ              (RMAIO_ADDR_FLUX_OBS_PARAMS_BASE + 1) // 模型临界速度
#define RMAIO_ADDR_FLUX_OBS_PARAMS_PLL_LPF_WC_HZ                (RMAIO_ADDR_FLUX_OBS_PARAMS_BASE + 2) // 锁相环速度滤波
#define RMAIO_ADDR_FLUX_OBS_PARAMS_COMP_VEL_HZ                  (RMAIO_ADDR_FLUX_OBS_PARAMS_BASE + 3) // 补偿速度
#define RMAIO_ADDR_FLUX_OBS_PARAMS_COMP_ID_A                    (RMAIO_ADDR_FLUX_OBS_PARAMS_BASE + 4) // 补偿电流
#define RMAIO_ADDR_FLUX_OBS_PARAMS_COMP_GAIN                    (RMAIO_ADDR_FLUX_OBS_PARAMS_BASE + 5) // 补偿增益
#define RMAIO_ADDR_FLUX_OBS_PARAMS_DEAD_VEL_HZ                  (RMAIO_ADDR_FLUX_OBS_PARAMS_BASE + 6) // 无传感器模式死区速度
#define RMAIO_ADDR_FLUX_OBS_PARAMS_FUSION_MIN_VEL_HZ            (RMAIO_ADDR_FLUX_OBS_PARAMS_BASE + 7) // 开始融合的速度

#define RMAIO_ADDR_TORQUE_CALIB_PARAMS_BASE                     (RMAIO_ADDR_PARAM_LIST_BASE + 282)        // 力矩标定参数
#define RMAIO_ADDR_TORQUE_CALIB_PARAMS_TORQUE_TO_CURRENT_A      (RMAIO_ADDR_TORQUE_CALIB_PARAMS_BASE + 0) // 转矩->电流多项式系数A
#define RMAIO_ADDR_TORQUE_CALIB_PARAMS_TORQUE_TO_CURRENT_B      (RMAIO_ADDR_TORQUE_CALIB_PARAMS_BASE + 1) // 转矩->电流多项式系数B
#define RMAIO_ADDR_TORQUE_CALIB_PARAMS_TORQUE_TO_CURRENT_C      (RMAIO_ADDR_TORQUE_CALIB_PARAMS_BASE + 2) // 转矩->电流多项式系数C
#define RMAIO_ADDR_TORQUE_CALIB_PARAMS_CURRENT_TO_TORQUE_X      (RMAIO_ADDR_TORQUE_CALIB_PARAMS_BASE + 3) // 电流->转矩多项式系数X
#define RMAIO_ADDR_TORQUE_CALIB_PARAMS_CURRENT_TO_TORQUE_Y      (RMAIO_ADDR_TORQUE_CALIB_PARAMS_BASE + 4) // 电流->转矩多项式系数Y
#define RMAIO_ADDR_TORQUE_CALIB_PARAMS_CURRENT_TO_TORQUE_Z      (RMAIO_ADDR_TORQUE_CALIB_PARAMS_BASE + 5) // 电流->转矩多项式系数Z
#define RMAIO_ADDR_TORQUE_CALIB_PARAMS_TORQUE_MAX               (RMAIO_ADDR_TORQUE_CALIB_PARAMS_BASE + 6) // 力矩限幅

#define RMAIO_ADDR_FRICTION_PARAMS_BASE                         (RMAIO_ADDR_PARAM_LIST_BASE + 305)    // 摩擦补偿参数
#define RMAIO_ADDR_FRICTION_PARAMS_FC                           (RMAIO_ADDR_FRICTION_PARAMS_BASE + 0) // 库仑摩擦力
#define RMAIO_ADDR_FRICTION_PARAMS_FS                           (RMAIO_ADDR_FRICTION_PARAMS_BASE + 1) // 最大静摩擦力
#define RMAIO_ADDR_FRICTION_PARAMS_B                            (RMAIO_ADDR_FRICTION_PARAMS_BASE + 2) // 粘滞摩擦系数
#define RMAIO_ADDR_FRICTION_PARAMS_DEAD_VEL                     (RMAIO_ADDR_FRICTION_PARAMS_BASE + 3) // 死区速度
#define RMAIO_ADDR_FRICTION_PARAMS_CALI_FLAG                    (RMAIO_ADDR_FRICTION_PARAMS_BASE + 4) // 摩擦补偿校准成功标志
#define RMAIO_ADDR_FRICTION_PARAMS_PERCENT                      (RMAIO_ADDR_FRICTION_PARAMS_BASE + 5) // 摩擦补偿百分比

#define RMAIO_ADDR_TEMP_CUR_PARAMS_BASE                         (RMAIO_ADDR_PARAM_LIST_BASE + 327)    // 绕组温度电流参数
#define RMAIO_ADDR_TEMP_CUR_PARAMS_CUR_TO_TEMP5                 (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 0) // 五次多项式系数5
#define RMAIO_ADDR_TEMP_CUR_PARAMS_CUR_TO_TEMP4                 (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 1) // 五次多项式系数4
#define RMAIO_ADDR_TEMP_CUR_PARAMS_CUR_TO_TEMP3                 (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 2) // 五次多项式系数3
#define RMAIO_ADDR_TEMP_CUR_PARAMS_CUR_TO_TEMP2                 (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 3) // 五次多项式系数2
#define RMAIO_ADDR_TEMP_CUR_PARAMS_CUR_TO_TEMP1                 (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 4) // 五次多项式系数1
#define RMAIO_ADDR_TEMP_CUR_PARAMS_CUR_TO_TEMP0                 (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 5) // 五次多项式系数0
#define RMAIO_ADDR_TEMP_CUR_PARAMS_TEMP_MAX                     (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 6) // 温度积分系数最大值
#define RMAIO_ADDR_TEMP_CUR_PARAMS_NORMAL_CUR                   (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 7) // 开始估算的最小电流
#define RMAIO_ADDR_TEMP_CUR_PARAMS_MAX_IQ_LIMIT                 (RMAIO_ADDR_TEMP_CUR_PARAMS_BASE + 8) // 输入最大电流限制

#define RMAIO_ADDR_ERR_DECT_PARAMS_BASE                         (RMAIO_ADDR_PARAM_LIST_BASE + 352)     // 错误检测参数
#define RMAIO_ADDR_ERR_DECT_PARAMS_IQ_OVER_CUR                  (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 0)  // Iq保护电流
#define RMAIO_ADDR_ERR_DECT_PARAMS_IQ_OVER_CUR_S                (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 1)  // Iq保护电流时间 秒
#define RMAIO_ADDR_ERR_DECT_PARAMS_CHIP_OVER_TEMP               (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 2)  // 芯片过温保护阈值
#define RMAIO_ADDR_ERR_DECT_PARAMS_MOS_OVER_TEMP                (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 3)  // Mos过温保护阈值
#define RMAIO_ADDR_ERR_DECT_PARAMS_COIL_OVER_TEMP               (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 4)  // 绕组过温保护阈值
#define RMAIO_ADDR_ERR_DECT_PARAMS_OVER_TEMP_S                  (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 5)  // 过温保护时间 秒
#define RMAIO_ADDR_ERR_DECT_PARAMS_MOS_TEMP_WARN                (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 6)  // Mos温度警告阈值
#define RMAIO_ADDR_ERR_DECT_PARAMS_COIL_TEMP_WARN               (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 7)  // 绕组温度警告阈值
#define RMAIO_ADDR_ERR_DECT_PARAMS_POS_MAX_RAD                  (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 8)  // 位置限制最大值
#define RMAIO_ADDR_ERR_DECT_PARAMS_POS_MIN_RAD                  (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 9)  // 位置限制最小值
#define RMAIO_ADDR_ERR_DECT_PARAMS_MOS_OVER_TEMP_REC_LIMIT_MS   (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 10) // Mos过温恢复时间限制(ms)
#define RMAIO_ADDR_ERR_DECT_PARAMS_COIL_OVER_TEMP_REC_LIMIT_MS \
        (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 11) // 绕组过温恢复时间限制(ms)
#define RMAIO_ADDR_ERR_DECT_PARAMS_LOSS_PHASE_CHECK_MIN_VEL_RADS \
        (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 12)                                                // 缺相检测最小速度(rads)
#define RMAIO_ADDR_ERR_DECT_PARAMS_OVER_VBUS           (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 13) // 过压阈值
#define RMAIO_ADDR_ERR_DECT_PARAMS_UNDER_VBUS          (RMAIO_ADDR_ERR_DECT_PARAMS_BASE + 14) // 低压阈值

#define RMAIO_ADDR_ACTUATOR_TYPE                       (RMAIO_ADDR_PARAM_LIST_BASE + 1008) // 执行器类型

#define RMAIO_ADDR_ACTUATOR_SUBVERSION                 (RMAIO_ADDR_PARAM_LIST_BASE + 1016) // 执行器子版本

/*---------------------------------- REAL TIME ----------------------------------*/
#define RMAIO_ADDR_REAL_TIME_BASE                      1024 // 实时数据基地址

#define RMAIO_ADDR_REAL_TIME_CONTROL_BASE              (RMAIO_ADDR_REAL_TIME_BASE + 0)         // 控制相关
#define RMAIO_ADDR_REAL_TIME_CONTROL_MODE              (RMAIO_ADDR_REAL_TIME_CONTROL_BASE + 0) // 控制模式
#define RMAIO_ADDR_REAL_TIME_CONTROL_WORD              (RMAIO_ADDR_REAL_TIME_CONTROL_BASE + 1) // 控制字
#define RMAIO_ADDR_REAL_TIME_WORK_MODE                 (RMAIO_ADDR_REAL_TIME_CONTROL_BASE + 2) // 反馈工作模式

#define RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_BASE         (RMAIO_ADDR_REAL_TIME_BASE + 10)             // 实时设置
#define RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_P            (RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_BASE + 0) // 位置
#define RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_V            (RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_BASE + 1) // 速度
#define RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_C            (RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_BASE + 2) // 电流
#define RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_T            (RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_BASE + 3) // 力矩
#define RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_V_FF         (RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_BASE + 4) // 速度前馈
#define RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_C_FF         (RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_BASE + 5) // 电流前馈
#define RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_T_FF         (RMAIO_ADDR_REAL_TIME_SET_PVCT_FFD_BASE + 6) // 力矩前馈

#define RMAIO_ADDR_REAL_TIME_GET_PVCT_BASE             (RMAIO_ADDR_REAL_TIME_BASE + 25)         // 实时获取
#define RMAIO_ADDR_REAL_TIME_GET_PVCT_P                (RMAIO_ADDR_REAL_TIME_GET_PVCT_BASE + 0) // 位置
#define RMAIO_ADDR_REAL_TIME_GET_PVCT_V                (RMAIO_ADDR_REAL_TIME_GET_PVCT_BASE + 1) // 速度
#define RMAIO_ADDR_REAL_TIME_GET_PVCT_C                (RMAIO_ADDR_REAL_TIME_GET_PVCT_BASE + 2) // 电流
#define RMAIO_ADDR_REAL_TIME_GET_PVCT_T                (RMAIO_ADDR_REAL_TIME_GET_PVCT_BASE + 3) // 力矩
#define RMAIO_ADDR_REAL_TIME_GET_PVCT_TE               (RMAIO_ADDR_REAL_TIME_GET_PVCT_BASE + 4) // 电磁转矩

#define RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_BASE          (RMAIO_ADDR_REAL_TIME_BASE + 37)            // PID参数
#define RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_P_KP          (RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_BASE + 0) // 位置比例增益
#define RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_V_KP          (RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_BASE + 1) // 速度比例增益
#define RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_V_KI          (RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_BASE + 2) // 速度积分增益
#define RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_PD_KP         (RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_BASE + 3) // PD比例增益
#define RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_PD_KD         (RMAIO_ADDR_REAL_TIME_PIDPD_PARAM_BASE + 4) // PD微分增益

#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE           (RMAIO_ADDR_REAL_TIME_BASE + 50)           // 错误码
#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_ERROR1         (RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE + 0) // 错误1
#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_ERROR2         (RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE + 1) // 错误2
#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_ERROR3         (RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE + 2) // 错误3
#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_ERROR4         (RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE + 3) // 错误4
#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_ERROR5         (RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE + 4) // 错误5
#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_ERROR6         (RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE + 5) // 错误6
#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_ERROR7         (RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE + 6) // 错误7
#define RMAIO_ADDR_REAL_TIME_ERROR_CODE_ERROR8         (RMAIO_ADDR_REAL_TIME_ERROR_CODE_BASE + 7) // 错误8

#define RMAIO_ADDR_REAL_TIME_POWER_STATUS_BASE         (RMAIO_ADDR_REAL_TIME_BASE + 58)             // 功率状态
#define RMAIO_ADDR_REAL_TIME_POWER_STATUS_TEMP_MOS     (RMAIO_ADDR_REAL_TIME_POWER_STATUS_BASE + 0) // mos温度
#define RMAIO_ADDR_REAL_TIME_POWER_STATUS_TEMP_COIL    (RMAIO_ADDR_REAL_TIME_POWER_STATUS_BASE + 1) // coil温度
#define RMAIO_ADDR_REAL_TIME_POWER_STATUS_VBUS         (RMAIO_ADDR_REAL_TIME_POWER_STATUS_BASE + 2) // 母线电压

#define RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_BASE (RMAIO_ADDR_REAL_TIME_BASE + 69) // 通信超时保护
#define RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_TIMEOUT_MS \
        (RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_BASE + 0) // 通信超时保护时间(ms)
#define RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_P_KP \
        (RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_BASE + 1) // 通信超时保护位置比例增益
#define RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_V_KP \
        (RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_BASE + 2) // 通信超时保护速度比例增益
#define RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_V_KI \
        (RMAIO_ADDR_REAL_TIME_COMM_TIMEOUT_PROTECT_BASE + 3) // 通信超时保护速度积分增益

/*---------------------------------- COMM DATA ----------------------------------*/
#define RMAIO_ADDR_COMM_DATA_BASE                          1280 // 通信数据基地址

#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_BASE              (RMAIO_ADDR_COMM_DATA_BASE + 0)                   // 通信数据订阅配置
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_NUM          (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_BASE + 0)       // 订阅条目数量
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_KEEPALIVE_TIME_MS (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_BASE + 1)       // 订阅保持时间
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_REMOTE_IP         (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_BASE + 2)       // 远端IPv4地址
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_REMOTE_PORT       (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_BASE + 3)       // 远端UDP端口
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE         (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_BASE + 4)       // 订阅条目信息
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_NUM_MAX      12                                                // 最大订阅条目数量
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_0            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 0)  // 订阅条目0
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_1            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 1)  // 订阅条目1
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_2            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 2)  // 订阅条目2
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_3            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 3)  // 订阅条目3
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_4            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 4)  // 订阅条目4
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_5            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 5)  // 订阅条目5
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_6            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 6)  // 订阅条目6
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_7            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 7)  // 订阅条目7
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_8            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 8)  // 订阅条目8
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_9            (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 9)  // 订阅条目9
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_10           (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 10) // 订阅条目10
#define RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_11           (RMAIO_ADDR_COMM_DATA_SUBS_CONFIG_ITEM_BASE + 11) // 订阅条目11
